### ISSUE TITLE
moulinette issue during install

### ISSUE THREAD

**Issue by brimwats** [YunoHost-Apps/adguardhome_ynh#17]
I get this issue during install—is it a YNH bug or this app?

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/moulinette/interfaces/api.py", line 484, in process
    ret = self.actionsmap.process(arguments, timeout=30, route=_route)
  File "/usr/lib/python3/dist-packages/moulinette/actionsmap.py", line 600, in process
    return func(**arguments)
  File "/usr/lib/moulinette/yunohost/log.py", line 380, in func_wrapper
    result = func(*args, **kwargs)
  File "/usr/lib/moulinette/yunohost/app.py", line 905, in app_install
    args_odict = _parse_args_from_manifest(manifest, "install", args=args_dict)
  File "/usr/lib/moulinette/yunohost/app.py", line 2670, in _parse_args_from_manifest
    return _parse_args_in_yunohost_format(args, action_args)
  File "/usr/lib/moulinette/yunohost/app.py", line 2979, in _parse_args_in_yunohost_format
    parser = ARGUMENTS_TYPE_PARSERS[question.get("type", "string")]()
KeyError: 'ad_user'
```

**Comment by 4abhinavjain** [comment]
I tried today and got the same error on YH 4.2.7 on x86

Traceback (most recent call last):                                                                                                                                      
  File "/usr/bin/yunohost", line 72, in <module>                                                                                                                        
    parser=parser                                                                                                                                                       
  File "/usr/lib/moulinette/yunohost/__init__.py", line 25, in cli                                                                                                      
    ret = moulinette.cli(args, output_as=output_as, timeout=timeout, top_parser=parser)                                                                                 
  File "/usr/lib/python3/dist-packages/moulinette/__init__.py", line 120, in cli                                                                                        
    args, output_as=output_as, timeout=timeout                                                                                                                          
  File "/usr/lib/python3/dist-packages/moulinette/interfaces/cli.py", line 502, in run                                                                                  
    ret = self.actionsmap.process(args, timeout=timeout)                                                                                                                
  File "/usr/lib/python3/dist-packages/moulinette/actionsmap.py", line 600, in process                                                                                  
    return func(**arguments)                                                                                                                                            
  File "/usr/lib/moulinette/yunohost/log.py", line 380, in func_wrapper                                                                                                 
    result = func(*args, **kwargs)                                                                                                                                      
  File "/usr/lib/moulinette/yunohost/app.py", line 913, in app_install                                                                                                  
    args_odict = _parse_args_from_manifest(manifest, "install", args=args_dict)                                                                                         
  File "/usr/lib/moulinette/yunohost/app.py", line 2678, in _parse_args_from_manifest                                                                                   
    return _parse_args_in_yunohost_format(args, action_args)                                                                                                            
  File "/usr/lib/moulinette/yunohost/app.py", line 2987, in _parse_args_in_yunohost_format                                                                              
    parser = ARGUMENTS_TYPE_PARSERS[question.get("type", "string")]()                                                                                                   
KeyError: 'ad_user'

**Comment by dumprop** [comment]
Today I installed without any issue

**Comment by kay0u** [comment]
Should be fixed now
